name: Test Build Workflow

on:
  workflow_dispatch:

jobs:
  test-cmake-workflow:
    uses: ./.github/workflows/cmake.yml
    with:
      enable-linux: true
      lib-name: TestLib
      repo: JunaMeinhold/cmake-actions
      repo-tag: v1.x.x
      bin-name-linux: dummy.so
      bin-name-linux-normalized: dummy.so 
      bin-name-android: dummy.so
      bin-name-android-normalized: dummy.so
      bin-name-windows: Release/dummy.dll
      bin-name-windows-normalized: dummy.dll
      bin-name-osx: dummy.dylib
      bin-name-osx-normalized: dummy.dylib
      use-vcpkg: true
      vcpkg-packages: utf8cpp